---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: towfiqueahmmed/restauranty-auth:v1.0.1
        ports:
        - containerPort: 3001
        env:
        - name: SECRET
          value: "MySecret1!"
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/resturanty"
        - name: PORT
          value: "3001"
          
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
