version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - restauranty-net

  auth:
    image: towfiqueahmmed/restauranty-auth:v1.0.1
    container_name: auth
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - restauranty-net
    depends_on:
      - mongo

  discounts:
    image: towfiqueahmmed/restauranty-discount:v1.0.1
    container_name: discounts
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - restauranty-net
    depends_on:
      - mongo

  items:
    image: towfiqueahmmed/restauranty-items:v1.0.1
    container_name: items
    restart: unless-stopped
    ports:
      - "3003:3003"
    networks:
      - restauranty-net
    depends_on:
      - mongo

  client:
    image: towfiqueahmmed/restauranty-client
    container_name: client
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - restauranty-net
    depends_on:
      - auth
      - discounts
      - items

  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - restauranty-net
    depends_on:
      - auth
      - discounts
      - items
      - client

networks:
  restauranty-net:
    driver: bridge
    name: restauranty-net

volumes:
  mongo-data:
