---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: towfiqueahmmed/restauranty-client:v1.0.5   # updated version after rebuild
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "https://2fik.diogohack.shop"
            - name: REACT_APP_SERVER_AUTH_URL
              value: "https://auth.2fik.diogohack.shop"
            - name: REACT_APP_SERVER_ITEMS_URL
              value: "https://items.2fik.diogohack.shop"
            - name: REACT_APP_SERVER_DISCOUNTS_URL
              value: "https://discounts.2fik.diogohack.shop"

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
