apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deployment
  labels:
    app: items
spec:
  replicas: 2
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
      - name: items
        image: towfiqueahmmed/restauranty-items:v1.0.1
        ports:
        - containerPort: 3003
        env:
        # Sensitive values from Secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: SECRET
        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: CLOUD_API_KEY
        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: CLOUD_API_SECRET
        # Non-sensitive value from ConfigMap
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: MONGODB_URI
