apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restauranty-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /   # move here, applies to all paths unless overridden
spec:
  rules:
  - host: 2fik.diogohack.shop
    http:
      paths:
        # API paths — exact, no rewrite
        - path: /api/auth
          pathType: Prefix
          backend:
            service:
              name: auth-service
              port:
                number: 3001
        - path: /api/discounts
          pathType: Prefix
          backend:
            service:
              name: discounts-service
              port:
                number: 3002
        - path: /api/items
          pathType: Prefix
          backend:
            service:
              name: items-service
              port:
                number: 3003
        # SPA — catch-all for all other paths
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client-service
              port:
                number: 80
