apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restauranty-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 2fik.diogohack.shop
    http:
      paths:
      # Explicit /login route
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 3001
      # Auth routes
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 3001
      # Discounts route
      - path: /discounts
        pathType: Prefix
        backend:
          service:
            name: discounts-service
            port:
              number: 3002
      # Items route
      - path: /items
        pathType: Prefix
        backend:
          service:
            name: items-service
            port:
              number: 3003
      # Catch-all route to frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 80
