name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Reset Docker builder
        run: |
          docker buildx rm mybuilder || true
          docker buildx create --use --name mybuilder

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build backend images
        run: |
          docker buildx build --builder mybuilder --load -t towfiqueahmmed/restauranty-auth:${{ github.sha }} ./backend/auth
          docker buildx build --builder mybuilder --load -t towfiqueahmmed/restauranty-discounts:${{ github.sha }} ./backend/discounts
          docker buildx build --builder mybuilder --load -t towfiqueahmmed/restauranty-items:${{ github.sha }} ./backend/items

      - name: Build frontend image
        working-directory: ./client
        run: |
          npm ci
          CI=false npm run build
          docker buildx build --builder mybuilder --build-arg REACT_APP_SERVER_URL=https://2fik.diogohack.shop --load -t towfiqueahmmed/restauranty-client:${{ github.sha }} .

      - name: Run tests
        run: |
          echo "Run your tests here"

      - name: Verify images
        run: docker images

      - name: Push images
        run: |
          for img in auth discounts items client; do
            docker push towfiqueahmmed/restauranty-$img:${{ github.sha }}
          done

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      # --- Apply Secrets and ConfigMaps first ---
      - name: Apply Secrets and ConfigMaps
        run: |
          kubectl apply -f k8s/secrets/sensitive-secret.yml
          kubectl apply -f k8s/secrets/non-sensitive-secret.yml

      # --- Apply MongoDB PVC first ---
      - name: Apply MongoDB PVC
        run: |
          kubectl apply -f k8s/volume/mongo-pvc.yml

      # --- Apply backend & client Deployments ---
      - name: Apply Deployments
        run: |
          kubectl apply -f k8s/base/

      # --- Update images for CI build ---
      - name: Update Deployment images
        run: |
          kubectl set image deployment/auth-deployment auth=towfiqueahmmed/restauranty-auth:${{ github.sha }}
          kubectl set image deployment/discounts-deployment discounts=towfiqueahmmed/restauranty-discounts:${{ github.sha }}
          kubectl set image deployment/items-deployment items=towfiqueahmmed/restauranty-items:${{ github.sha }}
          kubectl set image deployment/client-deployment client=towfiqueahmmed/restauranty-client:${{ github.sha }}

      # --- Apply NetworkPolicy and Ingress ---
      - name: Apply NetworkPolicy
        run: |
          kubectl apply -f k8s/policy/restauranty-networkpolicies.yml

      - name: Apply Ingress
        run: |
          kubectl apply -f k8s/ingress/restauranty-ingress.yml
