name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build images
        run: |
          docker build -t towfiqueahmmed/restauranty-auth:${{ github.sha }} ./backend/auth
          docker build -t towfiqueahmmed/restauranty-discount:${{ github.sha }} ./backend/discounts
          docker build -t towfiqueahmmed/restauranty-items:${{ github.sha }} ./backend/items
          docker build -t towfiqueahmmed/restauranty-client:${{ github.sha }} ./client

      - name: Run tests
        run: |
          echo "Run your tests here"

      - name: Push images
        run: |
          docker push towfiqueahmmed/restauranty-auth:${{ github.sha }}
          docker push towfiqueahmmed/restauranty-discount:${{ github.sha }}
          docker push towfiqueahmmed/restauranty-items:${{ github.sha }}
          docker push towfiqueahmmed/restauranty-client:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy images to AKS
      run: |
        kubectl set image deployment/auth-deployment auth=towfiqueahmmed/restauranty-auth:${{ github.sha }}
        kubectl set image deployment/discounts-deployment discounts=towfiqueahmmed/restauranty-discount:${{ github.sha }}
        kubectl set image deployment/items-deployment items=towfiqueahmmed/restauranty-items:${{ github.sha }}
        kubectl set image deployment/client-deployment client=towfiqueahmmed/restauranty-client:${{ github.sha }}
